require_relative('../models/bookings.rb')
require_relative('../models/classes.rb')
require_relative('../models/members.rb')
require('pry-byebug')

Booking.delete_all()
Classe.delete_all()
Member.delete_all()

member1 = Member.new({'first_name' => 'Bob', 'last_name' => 'Smith', 'age' => '21'})
member1.save()
member2 = Member.new({'first_name' => 'Jess', 'last_name' => 'Klien', 'age' => '34'})
member2.save()
member3 = Member.new({'first_name' => 'Frank', 'last_name' => 'Beverage', 'age' => '46'})
member3.save()

class1 = Classe.new({'name' => 'Spin', 'type' => 'Cycle', 'capacity' => '30', 'time' => '18:00'})
class1.save()
class2 = Classe.new({'name' => 'BodyPump', 'type' => 'Weight', 'capacity' => '25', 'time' => '19:30'})
class2.save()
class3 = Classe.new({'name' => 'Yoga', 'type' => 'relax', 'capacity' => '20', 'time' => '16:00'})
class3.save()

booking1 = Booking.new({'member_id' => member1.id(), 'class_id' => class1.id})
booking1.save()
booking2 = Booking.new({'member_id' => member1.id(), 'class_id' => class2.id})
booking2.save()
booking3 = Booking.new({'member_id' => member2.id(), 'class_id' => class3.id})
booking3.save()
booking4 = Booking.new({'member_id' => member2.id(), 'class_id' => class1.id})
booking4.save()
booking5 = Booking.new({'member_id' => member3.id(), 'class_id' => class2.id})
booking5.save()
booking6 = Booking.new({'member_id' => member3.id(), 'class_id' => class3.id})
booking6.save()
